# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unoserver/v1/service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aunoserver/v1/service.proto\x12\x0cunoserver.v1\"\x88\x02\n\x0e\x43onvertRequest\x12\x13\n\x06inpath\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06indata\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x12\x14\n\x07outpath\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x12\n\nconvert_to\x18\x04 \x01(\t\x12\x17\n\nfiltername\x18\x05 \x01(\tH\x03\x88\x01\x01\x12\x16\n\x0e\x66ilter_options\x18\x06 \x03(\t\x12\x14\n\x0cupdate_index\x18\x07 \x01(\x08\x12\x19\n\x0cinfiltername\x18\x08 \x01(\tH\x04\x88\x01\x01\x42\t\n\x07_inpathB\t\n\x07_indataB\n\n\x08_outpathB\r\n\x0b_filternameB\x0f\n\r_infiltername\"3\n\x0f\x43onvertResponse\x12\x14\n\x07outdata\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x42\n\n\x08_outdata\"\xde\x01\n\x0e\x43ompareRequest\x12\x14\n\x07oldpath\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07olddata\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x12\x14\n\x07newpath\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x14\n\x07newdata\x18\x04 \x01(\x0cH\x03\x88\x01\x01\x12\x14\n\x07outpath\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x15\n\x08\x66iletype\x18\x06 \x01(\tH\x05\x88\x01\x01\x42\n\n\x08_oldpathB\n\n\x08_olddataB\n\n\x08_newpathB\n\n\x08_newdataB\n\n\x08_outpathB\x0b\n\t_filetype\"3\n\x0f\x43ompareResponse\x12\x14\n\x07outdata\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x42\n\n\x08_outdata2\xa6\x01\n\x10UnoServerService\x12H\n\x07\x43onvert\x12\x1c.unoserver.v1.ConvertRequest\x1a\x1d.unoserver.v1.ConvertResponse\"\x00\x12H\n\x07\x43ompare\x12\x1c.unoserver.v1.CompareRequest\x1a\x1d.unoserver.v1.CompareResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unoserver.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONVERTREQUEST']._serialized_start=45
  _globals['_CONVERTREQUEST']._serialized_end=309
  _globals['_CONVERTRESPONSE']._serialized_start=311
  _globals['_CONVERTRESPONSE']._serialized_end=362
  _globals['_COMPAREREQUEST']._serialized_start=365
  _globals['_COMPAREREQUEST']._serialized_end=587
  _globals['_COMPARERESPONSE']._serialized_start=589
  _globals['_COMPARERESPONSE']._serialized_end=640
  _globals['_UNOSERVERSERVICE']._serialized_start=643
  _globals['_UNOSERVERSERVICE']._serialized_end=809
# @@protoc_insertion_point(module_scope)
